name: Deploy Frontend to AWS S3 & CloudFront

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Cambia esto si tu S3 y CloudFront están en otra región

      - name: Construir el proyecto
        run: |
          npm install
          npm run build  # Ajusta esto según tu framework (React, Vue, Angular, etc.)

      - name: Subir archivos a S3 con cifrado AES-256
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete --sse AES256

      - name: Invalida caché en CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

