name: Rollback Release
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag to rollback'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout specific tag
        run: git checkout ${{ github.event.inputs.release_tag }}

    #   - name: Setup AWS CLI
    #     uses: aws-actions/configure-aws-credentials@v3
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: us-east-1

    #   - name: Deploy to Amplify
    #     run: amplify publish --yes
